//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectMitre.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hardware_Additions
    {
        public int id { get; set; }
        public string result { get; set; }
        public string checked_device { get; set; }
        public int customer_id { get; set; }
        public System.DateTime date { get; set; }
    
        public virtual Customers Customers { get; set; }
    }
}
