//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProjectMitre.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MitreEntities : DbContext
    {
        public MitreEntities()
            : base("name=MitreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Accounts> Accounts { get; set; }
        public virtual DbSet<Attacks> Attacks { get; set; }
        public virtual DbSet<Credentials_From_Password_Stores> Credentials_From_Password_Stores { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Hardware_Additions> Hardware_Additions { get; set; }
        public virtual DbSet<Harmful_Applications> Harmful_Applications { get; set; }
        public virtual DbSet<MAC_Addresses> MAC_Addresses { get; set; }
    }
}
